pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'recover' }
    stages {
        stage('Test') {
            options { timeout(time: 95, unit: 'SECONDS')}
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}